### ISSUE TITLE
Add Qt WeakPartialMethodSlot from typhos

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsutils#79]
## Expected Behavior
typhos has a useful utility, WeakPartialMethodSlot
>     A PyQt-compatible slot for a partial method.
>
>    This utility handles deleting the connection when the method class instance
>    gets garbage collected. This avoids cycles in the garbage collector
>    that would prevent the instance from being garbage collected prior to the
>    program exiting.

https://github.com/pcdshub/typhos/blob/4ad54e7d8e94487c89b31c499e810b9cb00ca4a2/typhos/utils.py#L517

We can use it in multiple applications so it should be moved up to pcdsutils

**Comment by klauer** [comment]
That's a good point - it should include `*new_args` after `*self.partial_args`

**Comment by tangkong** [comment]
closed by #80
